### ISSUE TITLE
Is it Expected for FireEdge to Be Removed During TNLCM Installation?

### ISSUE THREAD

**Issue by tdelkand** [6G-SANDBOX/TNLCM#71]
Hello,

During the installation of TNLCM using the installation script (deploy_vm.sh), I noticed that FireEdge is being removed as part of the installation process. I’m unsure if this is expected behavior or if it’s causing an unintended issue.

I would like to confirm whether the removal of FireEdge is intentional during the TNLCM installation, or if there is a specific reason why it is being removed. If it's not expected, I would appreciate guidance on how to retain FireEdge while successfully installing TNLCM.

Thank you!

**Comment by CarlosAndreo** [comment]
Hello,

I have not had that happen to me before. Just in case, I ran the script from scratch on an empty vm and it didn't prompt me for anything FireEdge related. The `deploy_vm.sh` script just configures the environment to start TNLCM, so it is not related to FireEdge.

**Comment by tdelkand** [comment]
Hello,

Thank you for your response. I wanted to share some additional details for further clarification. If you provide me with an email address, I can send you the logs generated while running the deploy_vm.sh script.

In the logs, I noticed entries indicating the removal of opennebula-fireedge and several related packages, including nodejs-doc and node-acorn, along with a note about dependency issues.

I hope this information helps with your investigation.

Thank you!

**Comment by CarlosAndreo** [comment]
Hi,

The issue is likely due to **incompatibilities between Node.js versions**. TNLCM requires the latest stable version of Node.js (currently version 20), while OpenNebula FireEdge relies on Node.js version 12. This mismatch may cause dependency conflicts, leading to the removal of FireEdge-related packages during the installation of TNLCM.

**Proposed solution:** 

Perform the installation of TNLCM on a virtual machine that does not have OpenNebula's frontend (FireEdge) installed. This would prevent dependency conflicts and ensure that both applications can operate with their required Node.js versions.

Thanks!
